# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.27
# 

Name:       qtgeoservices_osmscoutoffline

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    QtGeoServices OSM Scout Offline with Sight Safary routing
Version:    0.5.0
Release:    1
Group:      System/Libraries
License:    BSD-3-Clause
URL:        https://github.com/osanwe/qtgeoservices-osmscoutoffline
Source0:    %{name}-%{version}.tar.bz2
Source100:  qtgeoservices_osmscoutoffline.yaml
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Location)
BuildRequires:  pkgconfig(Qt5Positioning)
BuildRequires:  pkgconfig(Qt5Network)

%description
QtGeoServices OSM Scout Offline with Sight Safary routing


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre

%qtc_qmake5 

%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

%files
%defattr(-,root,root,-)
%{_libdir}/qt5/plugins/geoservices/libqtgeoservices_osmscoutoffline.so
# >> files
# << files
